"""
Job Board Routes

HR manages job postings that were auto-generated by the JIRA → skill-match
pipeline. Postings start in 'limbo', HR approves them to publish.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel

from api.deps import require_role
from ai.text_cleanup import cleanup_text
from core.database import get_supabase_admin
from models.user import User, UserRole

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/job-board", tags=["Job Board"])


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _sanitize_posting_row(row: dict) -> dict:
    cleaned_description = cleanup_text(str(row.get("description") or ""))
    cleaned_reasoning = cleanup_text(str(row.get("ai_reasoning") or ""))
    return {
        **row,
        "description": cleaned_description["text"],
        "ai_reasoning": cleaned_reasoning["text"],
        "manual_review_needed": bool(cleaned_description["needs_manual_review"]),
        "flagged_terms": cleaned_description["flagged_terms"],
    }


def _with_internal_match(row: dict, assignment_map: dict[str, dict]) -> dict:
    assignment_id = str(row.get("jira_task_assignment_id") or "")
    assignment = assignment_map.get(assignment_id)
    if not assignment:
        return row

    match_score = float(assignment.get("match_score") or 0.0)
    internal_match = {
        "fit_percent": int(round(match_score * 100)),
        "recommended_name": assignment.get("recommended_assignee_name"),
        "recommended_email": assignment.get("recommended_assignee_email"),
        "status": assignment.get("status"),
        "ai_reasoning": assignment.get("ai_reasoning") or "",
        "no_internal_match": str(assignment.get("status") or "") == "no_match" or match_score < 0.4,
    }
    return {**row, "internal_match": internal_match}


# ── Schemas ───────────────────────────────────────────────────────────────────

class JobPostingUpdate(BaseModel):
    title: str | None = None
    description: str | None = None
    required_skills: list[str] | None = None
    workplace_type: str | None = None
    employment_type: str | None = None


class ApproveJobRequest(BaseModel):
    notes: str | None = None


class RejectJobRequest(BaseModel):
    reason: str


# ── Routes ────────────────────────────────────────────────────────────────────

@router.get("")
async def list_job_postings(
    status: str | None = None,
    current_user: User = Depends(require_role([UserRole.HR, UserRole.LEADERSHIP])),
):
    """List job postings. HR sees all; filter by status with ?status=limbo|approved|closed."""
    sb = get_supabase_admin()
    try:
        q = sb.table("job_postings").select("*").order("created_at", desc=True)
        if status:
            q = q.eq("status", status)
        r = q.execute()
        postings = [_sanitize_posting_row(row) for row in (r.data or [])]

        assignment_ids = [
            str(posting.get("jira_task_assignment_id"))
            for posting in postings
            if posting.get("jira_task_assignment_id")
        ]
        assignment_map: dict[str, dict] = {}
        if assignment_ids:
            ar = sb.table("jira_task_assignments").select(
                "id,recommended_assignee_name,recommended_assignee_email,match_score,status,ai_reasoning"
            ).in_("id", assignment_ids).execute()
            assignment_map = {str(row.get("id")): row for row in (ar.data or [])}

        postings = [_with_internal_match(posting, assignment_map) for posting in postings]
        return {"postings": postings, "total": len(postings)}
    except Exception as exc:
        logger.error("list_job_postings error: %s", exc)
        raise HTTPException(status_code=500, detail=str(exc))


@router.get("/public")
async def list_public_job_postings():
    """Public endpoint — returns only approved job postings (no auth required)."""
    sb = get_supabase_admin()
    try:
        r = sb.table("job_postings").select(
            "id,title,description,required_skills,workplace_type,employment_type,created_at"
        ).eq("status", "approved").order("created_at", desc=True).execute()
        return {"postings": [_sanitize_posting_row(row) for row in (r.data or [])]}
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))


@router.get("/limbo-count")
async def limbo_count(
    current_user: User = Depends(require_role([UserRole.HR, UserRole.LEADERSHIP])),
):
    """Quick badge count for sidebar."""
    sb = get_supabase_admin()
    try:
        r = sb.table("job_postings").select("id", count="exact").eq("status", "limbo").execute()
        return {"count": r.count or 0}
    except Exception:
        return {"count": 0}


@router.get("/{posting_id}")
async def get_job_posting(
    posting_id: str,
    current_user: User = Depends(require_role([UserRole.HR, UserRole.LEADERSHIP])),
):
    sb = get_supabase_admin()
    try:
        r = sb.table("job_postings").select("*").eq("id", posting_id).execute()
        if not r.data:
            raise HTTPException(status_code=404, detail="Job posting not found")
        return _sanitize_posting_row(r.data[0])
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))


@router.put("/{posting_id}")
async def update_job_posting(
    posting_id: str,
    body: JobPostingUpdate,
    current_user: User = Depends(require_role([UserRole.HR])),
):
    """Edit a job posting (only allowed while in limbo)."""
    sb = get_supabase_admin()
    try:
        r = sb.table("job_postings").select("status").eq("id", posting_id).execute()
        if not r.data:
            raise HTTPException(status_code=404, detail="Not found")
        if r.data[0]["status"] == "closed":
            raise HTTPException(status_code=400, detail="Cannot edit a closed posting")

        updates: dict = {"updated_at": _now()}
        if body.title is not None:
            updates["title"] = body.title
        if body.description is not None:
            updates["description"] = body.description
        if body.required_skills is not None:
            updates["required_skills"] = body.required_skills
        if body.workplace_type is not None:
            updates["workplace_type"] = body.workplace_type
        if body.employment_type is not None:
            updates["employment_type"] = body.employment_type

        sb.table("job_postings").update(updates).eq("id", posting_id).execute()
        return {"status": "updated", "posting_id": posting_id}
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))


@router.post("/{posting_id}/approve")
async def approve_job_posting(
    posting_id: str,
    body: ApproveJobRequest,
    current_user: User = Depends(require_role([UserRole.HR])),
):
    """HR approves a job posting — makes it visible on the public job board."""
    sb = get_supabase_admin()
    try:
        r = sb.table("job_postings").select("status,title").eq("id", posting_id).execute()
        if not r.data:
            raise HTTPException(status_code=404, detail="Not found")
        posting = r.data[0]
        if posting["status"] not in ("limbo",):
            raise HTTPException(status_code=400, detail=f"Already '{posting['status']}'")

        sb.table("job_postings").update({
            "status": "approved",
            "approved_by": current_user.email,
            "approved_at": _now(),
            "updated_at": _now(),
        }).eq("id", posting_id).execute()

        return {
            "status": "approved",
            "posting_id": posting_id,
            "title": posting["title"],
            "approved_by": current_user.email,
        }
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))


@router.post("/{posting_id}/close")
async def close_job_posting(
    posting_id: str,
    current_user: User = Depends(require_role([UserRole.HR])),
):
    """Mark a job posting as closed (filled or cancelled)."""
    sb = get_supabase_admin()
    try:
        sb.table("job_postings").update({
            "status": "closed",
            "updated_at": _now(),
        }).eq("id", posting_id).execute()
        return {"status": "closed", "posting_id": posting_id}
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))
